# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationConfigurationLookupFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.CharField(max_length=256)),
                ('record_number', models.IntegerField()),
                ('region', models.IntegerField()),
                ('data_policy_licence', models.IntegerField()),
                ('primary_station_id_scheme', models.IntegerField()),
                ('location_accuracy', models.FloatField()),
                ('location_method', models.TextField(max_length=256)),
                ('location_quality', models.IntegerField()),
                ('height_of_station_above_local_ground', models.FloatField(blank=True, null=True)),
                ('height_of_station_above_sea_level', models.FloatField(blank=True, null=True)),
                ('height_of_station_above_sea_level_accuracy', models.FloatField(blank=True, null=True)),
                ('sea_level_datum', models.FloatField(blank=True, null=True)),
                ('source_id', models.CharField(max_length=256)),
            ],
        ),
    ]
