# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-31 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationConfigurationLookupFields',
            fields=[
                ('primary_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('region', models.IntegerField()),
                ('data_policy_licence', models.IntegerField()),
                ('primary_station_id_scheme', models.IntegerField()),
                ('location_accuracy', models.FloatField()),
                ('location_method', models.TextField(max_length=256)),
                ('location_quality', models.IntegerField()),
                ('height_of_station_above_local_ground', models.FloatField(blank=True, null=True)),
                ('height_of_station_above_sea_level', models.FloatField(blank=True, null=True)),
                ('height_of_station_above_sea_level_accuracy', models.FloatField(blank=True, null=True)),
                ('sea_level_datum', models.FloatField(blank=True, null=True)),
                ('source_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
